baseURL = "https://a1v4.ro"
theme = "risotto"
title = "a1v4"
author = "a1v4"
copyright = "© a1v4"
paginate = 10
languageCode = "en"
defaultContentLanguage = "en"
enableInlineShortcodes = true
# Automatically add content sections to main menu
sectionPagesMenu = "main"

summaryLength = 20

[params]
noindex = false

[params.theme]
palette = "tokyo-night-dark"

# Sidebar: about/bio
[params.about]
title = "a1v4"
description = "Something here"
# unicode/emoji logo:
logo = "🍚"
# or use an image:
#logo_image = "images/rice.svg"

# Sidebar: social links
# Available icon sets:
# * FontAwesome 6 <https://fontawesome.com/> ('fa-brands', 'fa-normal', or 'fa-solid' for brands)
# * Academicons <https://jpswalsh.github.io/academicons> ('ai ai-')

[[params.socialLinks]]
icon = "fa-brands fa-github"
title = "GitHub"
url = "https://github.com/0xA1v4"

[[params.socialLinks]]
icon = "fa-solid fa-envelope"
title = "Email"
url = "mailto:alv@a1v4.ro"

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

# For hugo >= 0.60.0, enable inline HTML
[markup.goldmark.renderer]
unsafe = true

[markup]
  # Table of contents
  # Add toc = true to content front matter to enable
  [markup.tableOfContents]
    startLevel = 2
    endLevel   = 3
    ordered    = true
